language: node_js
sudo: required
script: "npm run test"
node_js:
  - "4"
  - "6"
  - "node"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

env:
  - CXX=g++-4.8